

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketbooking_db
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  
  web:
    build: .
    command: ["./wait-for.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
    # volumes:
    #   - ./wait-for.sh:/app/wait-for.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=ticketbooking_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=your_password


volumes:
  mysql-data:
